name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  http: ^1.2.1
  flutter_screenutil: ^5.9.3
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  share_plus: ^9.0.0
  flutter_svg: ^2.0.10+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
